# Generated by Django 4.0.4 on 2022-05-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markė', models.CharField(help_text='Įveskite automobilio markę', max_length=30, verbose_name='Markė')),
                ('modelis', models.CharField(help_text='Įveskite automobilio modelį', max_length=30, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilio Modelis',
                'verbose_name_plural': 'Automobilio Modeliai',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Įveskite valstybinį numerį', max_length=30, verbose_name='Valstybinis NR')),
                ('vin_kodas', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=30, verbose_name='VIN kodas')),
                ('klientas', models.CharField(help_text='Įveskite kliento vardą', max_length=30, verbose_name='Klientas')),
                ('aprašymas', models.TextField(default='', max_length=2000, verbose_name='Aprašymas')),
                ('automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servisas.automobiliomodelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą', max_length=30, verbose_name='Paslaugos pavadinimas')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Užsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Įveskite užsakymo datą', max_length=30, verbose_name='Užsakymo data')),
                ('suma', models.FloatField(help_text='Įveskite užsakymo sumą', max_length=30, verbose_name='Suma')),
                ('status', models.CharField(blank=True, choices=[('p', 'Patvirtinta'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atšaukta')], default='p', help_text='Statusas', max_length=1)),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servisas.automobilis')),
                ('paslauga', models.ManyToManyField(to='servisas.paslauga')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='UžsakymoEilutė',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.CharField(help_text='Įveskite kiekį', max_length=30, verbose_name='Kiekis')),
                ('kaina', models.FloatField(help_text='Įveskite užsakymo kainą', max_length=30, verbose_name='Kaina')),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servisas.paslauga')),
                ('užsakymas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eilutes', to='servisas.užsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo Eilutė',
                'verbose_name_plural': 'Užsakymo Eilutės',
            },
        ),
    ]
